server:
  port: 80

spring:
  # HTML Form 제공하지 않는 delete, put 메소드 사용
  mvc:
    hidden-method:
      filter:
        enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        hbm2ddl:
          auto: update
    defer-datasource-initialization: true

  # MariaDB 데이터베이스 사용 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/E1i4
    driver-class-name: org.mariadb.jdbc.Driver
    username: user
    password: password

    #HikariCP 설정
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: HikariPoolBBS